### ISSUE TITLE
Provide a way to more conveniently enable the endpoint options with pressing the TAB key

### ISSUE THREAD

**Issue by vrlgohel** [camel-tooling/camel-lsp-client-eclipse#29]
The current issue with this plugin is that  when i press the Ctrl+Space for CodeAssist, it provides the endpoint options, but then on selecting a particular option and pressing 'Enter' moves away to the next line in the xml editor. 
I have to press 'TAB' to select the popped up window, then press 'ENTER'. 

Also, this plugin does not work when Spring IDE is installed. If you have Spring Config Tooling, and the file is opened with spring xml editor, the plugin does not work.

**Comment by apupier** [comment]
the new line thing looks alike a bug in LSP4E as it is working on VSCode. I opened an issue in LSP4E: https://bugs.eclipse.org/bugs/show_bug.cgi?id=534092

**Comment by apupier** [comment]
I created a different issue for the Spring IDE compatibility: https://github.com/camel-tooling/camel-lsp-client-eclipse/issues/31

**Comment by apupier** [comment]
I do not reproduce anymore the move to the next line in xml editor
![noMoreGoingToNewLine](https://user-images.githubusercontent.com/1105127/114184263-ec869180-9944-11eb-8de8-6e1e907f986e.gif)
