### ISSUE TITLE
Filter suggestions according to typed text

### ISSUE THREAD

**Issue by tsedmik** [camel-tooling/camel-lsp-client-eclipse#36]
If user uses code completion feature and type some text or invoke code completion on partially typed text, proposed suggestions are not filtered according to the text (see attached screenshot)
![suggestions](https://user-images.githubusercontent.com/5408450/41585847-79c86dd8-73ab-11e8-9df8-9d3d86510e6d.png)

**Comment by apupier** [comment]
this is a limitation of Eclipse Client for Language Server (LSP4E)
If you call the completion yourself again after "fi" the list is filtered.

**Comment by tsedmik** [comment]
ok ... therefore, we can close this issue ;-)
