### ISSUE TITLE
Console for Camel LSP Server remains open after deletion of the project

### ISSUE THREAD

**Issue by tsedmik** [camel-tooling/camel-lsp-client-eclipse#44]
A new instance of Camel LSP Server is started with every project in the workspace (I have to open an XML file in the project). New Console is opened with it. If I close/delete the project, Camel LSP server instance is terminated (it may take some time but it is terminated after all), but the console remains open.

![console2](https://user-images.githubusercontent.com/5408450/42498739-50af76ca-842d-11e8-8404-1ee638312d65.gif)

**Comment by apupier** [comment]
I think it is a classical behavior of Eclipse.
If this behavior needs to be changed in the specific context of Language Servers, I would say that it needs to be done in [LSP4E](https://wiki.eclipse.org/LSP4E) project

**Comment by Postremus** [comment]
Facing the same problem here. 
I have to edit multiple pom.xml files today. For every file, a new console is opened, and never closed.
This behavior is especially annoing once you have to scroll through the list of consoles because too many of them are open.

In this example, the list is taking up the entire height of my screen.
![image](https://user-images.githubusercontent.com/1223135/51465620-8bc10d80-1d68-11e9-9e3a-8023af25e423.png)

**Comment by sorin-costea** [comment]
I can't believe it's Eclipse standard as I don't see any other behaving like Camel LSP:

- opens a new language server process for what it seems every XML file I have (not every project and not every Camel file)
- opens a new console for each process (good luck finding yours, see screenshot above)
- these consoles stay open forever and they also never show me anything
- after exiting Eclipse the language server processes stay open...

I just disabled the two Camel LSP servers in Eclipse settings, the hassle is much too big for the benefits. 
I'm using both Red Hat Developer Studio 12.9 and Spring Tool Suite 4.1 with different Java 1.8 versions, same behaviour.

**Comment by mickaelistria** [comment]
I guess the Camel Language Server does use the `logMessage()` operation which exactly requests client to log that to the user if not mistaken. So not invoking this method should avoid such logging.
About the multiplicity, the camel language server could investigate declaring support for workspaceFolders in its capabilities. This is used by LSP4E to determine whether to spawn a new LS or whether one can be reused for files which are under a different Eclipse project.

**Comment by apupier** [comment]
> I guess the Camel Language Server does use the `logMessage()` operation which exactly requests client to log that to the user if not mistaken. So not invoking this method should avoid such logging.

thanks. I created this PR to avoid this logging which is not very useful, especially for end users https://github.com/camel-tooling/camel-language-server/pull/205

I think that LSP4E should be able to close the different console when there is no more resources attached to it in the workspace. I will try to report an enhancement request soon (but we are too close to weekend time :p)

> About the multiplicity, the camel language server could investigate declaring support for workspaceFolders in its capabilities. This is used by LSP4E to determine whether to spawn a new LS or whether one can be reused for files which are under a different Eclipse project.

Thanks for the pointer. I created https://github.com/camel-tooling/camel-language-server/issues/206

**Comment by apupier** [comment]
The console is not opening anymore with latest version.

Thanks for the report @tsedmik and for the push @Postremus @sorin-costea and for the help @mickaelistria

**Comment by djelinek** [comment]
verified - Apache Camel LSP Client Extensions Plugin 1.0.0.201902121537
