### ISSUE TITLE
Duplicate options filtering does not working

### ISSUE THREAD

**Issue by djelinek** [camel-tooling/camel-lsp-client-eclipse#48]
Catched by [UI test](https://github.com/djelinek/camel-lsp-client-eclipse/blob/LSP-41/com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/CamelLSPCompletionTest.java).
Tests duplicate endpoint options are filtered out.

Environment:
- Eclipse Photon 4.8.0
- Tooling for Apache Camel 1.0.0.201810191014

Steps to reproduce:
1. Open [camel-context.xml](https://github.com/djelinek/camel-lsp-client-eclipse/blob/LSP-41/com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/resources/camel-context-cbr.xml) in XML editor
2. Set cursor to endpoint (for example `<from />`) and clear all options inside
3. Save editor
4. Execute ctrl+space
5. Content assistant is still empty or contains already used options

**Comment by apupier** [comment]
@djelinek I don't reproduce the error.
I don't understand why you say content assistant is still empty or contains already used options. it should never be empty and never provide options that are already used in the same URI.

the "delay" attribute is well filtered out here for instance:
![image](https://user-images.githubusercontent.com/1105127/47778947-460c2000-dcf8-11e8-8252-bcef65132a37.png)

**Comment by djelinek** [comment]
OK, it make sense, thanks for clarify it. In this case I will make changes in UI tests and this issue should be closed.

**Comment by djelinek** [comment]
Closing - Explained
