### ISSUE TITLE
create an online update site

### ISSUE THREAD

**Issue by lhein** [camel-tooling/camel-lsp-client-eclipse#5]
We should look for a way to create and publish the update site with each travis build

**Comment by apupier** [comment]
possible solution:
- github pages --> https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/pull/20

**Comment by apupier** [comment]
available on https://camel-tooling.github.io/camel-lsp-client-eclipse-update-site/ (working in Eclipse, 404 in browser because there is no index.html)
