### ISSUE TITLE
Fix tests on Travis which are failing with timeout

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-eclipse#76]
since few days.
I initially though tit was due to a PR related to Target platform update but in fact it is failing also for a modification of the readme, so seems related to the CI itself

**Comment by apupier** [comment]
The test CamelLSPStreamConnectionProviderIT is looping because it is waiting for "Connected to Language Server..." to be written on output which is no more the case since https://github.com/camel-tooling/camel-language-server/commit/d2cd4aac5c25bd476e30ff0f2cc911bcf4cfae20

**Comment by tsedmik** [comment]
verified with master branch
