### ISSUE TITLE
Update Travis CI build which has broken Java install

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-eclipse#82]
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
install-jdk.sh 2019-05-02
Expected feature release number in range of 9 to 13, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

**Comment by djelinek** [comment]
verified with master branch
